title: Manjin Kim
description: Ph.D student, POSTECH, South Korea.
show_downloads: false
google_analytics: UA-108144808-1
# theme: jekyll-theme-minimalist
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
